build-dev:
  image: node:12
  stage: build
  script:
    - export API_BASE_URL=https://mall-api.ms5149514.com
    - npm install
    - npm run build
  only:
    - dev
  artifacts:
    expire_in: 1 week
    paths:
      - ./

deploy-dev:
  image: alpine
  stage: deploy
  script:
    - rsync -rv --exclude-from 'deploy/exclude.txt' --delete -e 'ssh -p 2222' ./ $SERVER_TOKEN_TEST:${WEB_ROOT}lottery/${CI_PROJECT_NAME}
    - ssh $SERVER_TOKEN_TEST -p2222 -t "/home/laradock/.nvm/versions/node/v13.13.0/bin/pm2 restart lottery-mall-mobile"
  only:
    - dev
  before_script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY_TEST" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod -R 600 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS_TEST" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

build-master:
  image: node:12
  stage: build
  #when: manual
  script:
    - export API_BASE_URL=https://shop-pro.com/api
    - npm install
    - npm run build
  only:
    - master
  artifacts:
    expire_in: 1 week
    paths:
      - ./

deploy-master:
  image: alpine
  stage: deploy
  #when: manual
  script:
    - rsync -rv --exclude-from 'deploy/exclude.txt' --delete -e 'ssh -p 2222 -o ConnectTimeout=180' ./ $SERVER_TOKEN:${WEB_ROOT}${CI_PROJECT_NAME}
    - ssh $SERVER_TOKEN -p2222 -t "/home/laradock/.nvm/versions/node/v15.5.1/bin/pm2 restart mall-mobile"
  only:
    - master
  before_script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod -R 600 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
